name: Godot-ci Export"
on:
    push:
        tags:
         - v*.*

env:
    GODOT_VERSION: 4.3
    EXPORT_NAME: space-war
    PROJECT_PATH: .

jobs:
    make-release:
        - name: Make Release
          uses: softprops/action-gh-release@v2
          with:
              make_latest: true
              append_body: true
              name: ${{ env.EXPORT_NAME }} ${{ github.ref_name }}

    export-windows:
        name: Windows Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:4.3
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Setup
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mkdir -v -p ~/.config/
                mv /root/.config/godot ~/.config/godot
                mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
            - name: Windows Build
              run: |
                mkdir -v -p build/windows
                EXPORT_DIR="$(readlink -f build)"
                cd $PROJECT_PATH
                godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                append_body: true
                fail_on_unmatched_files: true
                files: |
                    build/windows/*.*

    export-linux:
        name: Linux Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:4.3
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Setup
          run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        - name: Linux Build
          run: |
            mkdir -v -p build/linux
            EXPORT_DIR="$(readlink -f build)"
            cd $PROJECT_PATH
            godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: space-war-linux
            path: build/linux

    export-mac:
        name: Mac Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:4.3
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Setup
          run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        - name: Mac Build
          run: |
            mkdir -v -p build/mac
            EXPORT_DIR="$(readlink -f build)"
            cd $PROJECT_PATH
            godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: space-war-mac
            path: build/mac
