name: Build Space War Game (Godot)
on:
    push:
        tags:
         - v*.*

# https://github.com/marketplace/actions/godot-ci
# https://github.com/marketplace/actions/checkout
# https://github.com/marketplace/actions/gh-release

env:
    GODOT_VERSION: 4.4.1
    EXPORT_NAME: space-war
    PROJECT_PATH: .

jobs:
    export-windows:
        name: Windows Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:4.4.1
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Setup
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mkdir -v -p ~/.config/
                mv /root/.config/godot ~/.config/godot
                mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
            - name: Windows Build
              run: |
                mkdir -v -p build/windows
                EXPORT_DIR="$(readlink -f build)"
                cd $PROJECT_PATH
                godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
                cd build/windows
                zip -r space-war-windows space-war.exe space-war.pck
            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                name: ${{ env.EXPORT_NAME }} ${{ github.ref_name }}
                make_latest: true
                append_body: true
                fail_on_unmatched_files: true
                files: |
                    build/windows/space-war-windows.zip

    export-linux:
        name: Linux Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Setup
          run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        - name: Linux Build
          run: |
            mkdir -v -p build/linux
            EXPORT_DIR="$(readlink -f build)"
            cd $PROJECT_PATH
            godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
            cd build/linux
            zip -r space-war-linux space-war.x86_64 space-war.pck
        - name: Upload Release
          uses: softprops/action-gh-release@v2
          with:
            make_latest: true
            append_body: true
            fail_on_unmatched_files: true
            files: |
                build/linux/space-war-linux.zip


    export-mac:
        name: Mac Export
        runs-on: ubuntu-22.04
        container:
            image: barichello/godot-ci:latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Setup
          run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        - name: Mac Build
          run: |
            mkdir -v -p build/mac
            EXPORT_DIR="$(readlink -f build)"
            cd $PROJECT_PATH
            godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME-mac.zip"
        - name: Upload Release
          uses: softprops/action-gh-release@v2
          with:
            make_latest: true
            append_body: true
            fail_on_unmatched_files: true
            files: |
                build/mac/space-war-mac.zip
